force-app/main/default/objects/MyObject__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <label>NewValue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MyObject__c/fields/OldValue__c.field-meta.xml
<CustomField>
    <fullName>OldValue__c</fullName>
    <label>OldValue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MyObject__c/fields/TrackedField__c.field-meta.xml
<CustomField>
    <fullName>TrackedField__c</fullName>
    <label>TrackedField</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MyObject__c/fields/TrackedObject__c.field-meta.xml
<CustomField>
    <fullName>TrackedObject__c</fullName>
    <label>TrackedObject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public without sharing class AccountTriggerHandler {
    public static void handle(List<Account> newList, Map<Id, Account> oldMap) {
        List<MyObject__c> records = new List<MyObject__c>();
        for (Account acct : newList) {
            Account oldAcct = null;
            if (oldMap != null) {
                oldAcct = oldMap.get(acct.Id);
            }
            MyObject__c trackingRec = new MyObject__c();
            trackingRec.Name = 'Account';
            trackingRec.TrackedObject__c = 'Account';
            trackingRec.TrackedField__c = 'Source';
            trackingRec.OldValue__c = oldAcct?.Source__c;
            trackingRec.NewValue__c = acct.Source__c;
            trackingRec.OwnerId = UserInfo.getUserId();
            records.add(trackingRec);
            
            trackingRec = new MyObject__c();
            trackingRec.Name = 'Account';
            trackingRec.TrackedObject__c = 'Account';
            trackingRec.TrackedField__c = 'Source Date';
            trackingRec.OldValue__c = oldAcct?.Source_Date__c?.format();
            trackingRec.NewValue__c = acct.Source_Date__c?.format();
            trackingRec.OwnerId = UserInfo.getUserId();
            records.add(trackingRec);
        }
        
        if (!records.isEmpty()) {
            try {
                insert records;
            } catch(Exception ex) {
                System.debug('AccountTriggerHandler.handle(): ' + ex.getMessage());
            }
        }
    }
}