force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Appointment records with physicians for patients</description>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <description>Date part of Start_Time__c</description>
    <formula>DATEVALUE(Start_Time__c)</formula>
    <inlineHelpText>Date part of Start_Time__c</inlineHelpText>
    <label>Appointment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End time of the appointment</description>
    <inlineHelpText>End time of the appointment</inlineHelpText>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Start time of the appointment</description>
    <inlineHelpText>Start time of the appointment</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Physician__c/Physician__c.object-meta.xml
<CustomObject>
    <description>Physicians for different subspecialties</description>
    <label>Physician</label>
    <nameField>
        <label>Physician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician__c/fields/Subspecialty__c.field-meta.xml
<CustomField>
    <fullName>Subspecialty__c</fullName>
    <description>Reference to a subspecialty</description>
    <inlineHelpText>Reference to a subspecialty</inlineHelpText>
    <label>Subspecialty</label>
    <referenceTo>Subspecialty__c</referenceTo>
    <relationshipLabel>Physicians</relationshipLabel>
    <relationshipName>Physicians</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subspecialty__c/Subspecialty__c.object-meta.xml
<CustomObject>
    <label>Subspecialty</label>
    <nameField>
        <label>Subspecialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subspecialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subspecialty__c/fields/Appointment_Price__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Price__c</fullName>
    <description>Price per appointment</description>
    <label>Appointment Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ScheduleApptController.cls
public without sharing class ScheduleApptController {
    @AuraEnabled(cacheable=true)
    public static List<Patient__c> getPatients(){
        return [SELECT Id, Name FROM Patient__c ORDER BY Name];
    }

    @AuraEnabled(cacheable=true)
    public static List<Subspecialty__c> getSubspecialties(){
        return [SELECT Id, Name, Appointment_Price__c FROM Subspecialty__c];
    }

    @AuraEnabled(cacheable=true) 
    public static List<Physician__c> getPhysicians(String subspecialtyId) {
        return [SELECT Id, Name FROM Physician__c WHERE Subspecialty__c = :subspecialtyId];
    }

    @AuraEnabled(cacheable=true)
    public static List<Appointment__c> getAppointments(String subspecialtyId, String strDate) {
        Date dt = Date.valueOf(strDate);    //strDate: '2021-09-01'
        return [SELECT Id, Start_Time__c, Physician__c FROM Appointment__c WHERE Appointment_Date__c =: dt AND Physician__r.Subspecialty__c =: subspecialtyId];
    }

    @AuraEnabled        //No (cacheable=true) to avoid in imperative call: LimitException: Too many DML statements: 1
    public static String saveAppointment(String startTime, String physicianId, String patientId) {
        String patientName = '';

        DateTime dt = DateTime.valueOf(startTime);      //startTime: '2021-09-01 08:30:00'
        Appointment__c appt = new Appointment__c();
        appt.Physician__c = physicianId;
        if (patientId != null && patientId != 'none') {
            appt.Patient__c = patientId;

            Patient__c p = [SELECT Name FROM Patient__c WHERE Id =: patientId LIMIT 1];
            patientName = p.Name + ' Appointment';
        }
        appt.Start_Time__c = dt;
        appt.End_Time__c = dt.addMinutes(30);
        appt.Name = patientName;

        insert appt;

        GoogleCalendar.bookPhysicianCalendar(appt.Id);

        //If single email limit per day exceeds, don't send email
        System.debug('saveAppointment(): getEmailInvocations(): ' + Limits.getEmailInvocations());
        System.debug('saveAppointment(): getLimitEmailInvocations(): ' + Limits.getLimitEmailInvocations());
        if (Limits.getEmailInvocations() < Limits.getLimitEmailInvocations()) {
            GoogleCalendar.sendPhysicianEmail(appt.Id);
        }
        else {
            System.debug('saveAppointment(): Single Emails Limit exceeds. Email not sent.');
        }

        return appt.Id;
    }
}