force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Appointment records with physicians for patients</description>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End time of the appointment</description>
    <inlineHelpText>End time of the appointment</inlineHelpText>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Start time of the appointment</description>
    <inlineHelpText>Start time of the appointment</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Physician__c/Physician__c.object-meta.xml
<CustomObject>
    <description>Physicians for different subspecialties</description>
    <label>Physician</label>
    <nameField>
        <label>Physician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician__c/fields/Gmail__c.field-meta.xml
<CustomField>
    <fullName>Gmail__c</fullName>
    <description>A physician&apos;s Gmail email address</description>
    <inlineHelpText>Gmail address</inlineHelpText>
    <label>Gmail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Physician__c/fields/Subspecialty__c.field-meta.xml
<CustomField>
    <fullName>Subspecialty__c</fullName>
    <description>Reference to a subspecialty</description>
    <inlineHelpText>Reference to a subspecialty</inlineHelpText>
    <label>Subspecialty</label>
    <referenceTo>Subspecialty__c</referenceTo>
    <relationshipLabel>Physicians</relationshipLabel>
    <relationshipName>Physicians</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subspecialty__c/Subspecialty__c.object-meta.xml
<CustomObject>
    <label>Subspecialty</label>
    <nameField>
        <label>Subspecialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subspecialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subspecialty__c/fields/Appointment_Price__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Price__c</fullName>
    <description>Price per appointment</description>
    <label>Appointment Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/GoogleCalendarTest.cls
@isTest
public class GoogleCalendarTest {
    @TestSetup
    public static void makeData(){
        Subspecialty__c ss = new Subspecialty__c();
        ss.Name = 'General Practice';
        ss.Appointment_Price__c = 100;
        insert ss;

        Physician__c ph = new Physician__c();
        ph.Name = 'Dr. Hyde';
        ph.Subspecialty__c = ss.Id;
        ph.Gmail__c = 'test@test.com';
        insert ph;

        Patient__c p = new Patient__c();
        p.Name = 'Peter Pan';
        insert p;

        Appointment__c appt = new Appointment__c();
        appt.Name = 'Peter Pan Appointment';
        appt.Physician__c = ph.Id;
        appt.Patient__c = p.Id;
        appt.Start_Time__c = DateTime.valueOf('2021-09-30 08:00:00');
        appt.End_Time__c = appt.Start_Time__c.addMinutes(30);
        insert appt;
    }

    @isTest
    public static void testSendPhysicianEmail() {
        Appointment__c appt = [SELECT Id FROM Appointment__c LIMIT 1];
        Test.startTest();
        GoogleCalendar.sendPhysicianEmail(appt.Id);
        Test.stopTest();
    }

    @isTest
    public static void testBookPhysicianCalendar() {
        Appointment__c appt = [SELECT Id FROM Appointment__c LIMIT 1];
        Test.startTest();
        GoogleCalendar.bookPhysicianCalendar(appt.Id);
        Test.stopTest();
    }
}